<?php

namespace Modules\Brand\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;
use Modules\Brand\Models\Brand;

class BrandFactory extends Factory
{
    protected $model = Brand::class;

    /**
     * One sentence per brand, picked at random. Written out rather than
     * generated by faker so the seeded catalogue reads like a real store
     * instead of lorem ipsum.
     *
     * @var list<string>
     */
    protected array $descriptions = [
        'Performance gear built for athletes who train year round.',
        'A specialist in durable equipment for team sports.',
        'Technical apparel designed for comfort over long sessions.',
        'Equipment trusted by clubs and national federations alike.',
        'Everyday sportswear with a focus on sustainable materials.',
        'Precision-made accessories for competition and training.',
    ];

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $name = $this->faker->unique()->company();

        return [
            'name' => $name,
            // The model derives a slug on save; setting it here keeps the
            // factory usable when model events are muted in a test.
            'slug' => Str::slug($name),
            'description' => $this->faker->randomElement($this->descriptions),
            'logo' => 'https://placehold.co/200x200/png',
            'is_active' => true,
            'is_new' => $this->faker->boolean(40),
            'order' => $this->faker->numberBetween(0, 100),
        ];
    }

    /**
     * A brand that exists but is hidden from the storefront.
     */
    public function inactive(): static
    {
        return $this->state(fn () => ['is_active' => false]);
    }

    /**
     * A brand carrying the "new" flag used by the landing page strip.
     */
    public function featured(): static
    {
        return $this->state(fn () => ['is_new' => true]);
    }
}
